_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-arm64
batch_size:
    value: 256
board_size:
    value: 8
dropout:
    value: 0.1
epochs:
    value: 10
grad_clip:
    value: 1
learning_rate_max:
    value: 0.01
learning_rate_min:
    value: 0.0001
num_channels:
    value: 512
num_episodes:
    value: 100
num_iterations:
    value: 200
num_mcts_sims:
    value: 800
